runtime: python310
service: bookstore-api

entrypoint: gunicorn -b :$PORT -k gevent -w 1 --timeout 120 --graceful-timeout 120 app:app

instance_class: F1

env_variables:
  API_KEY: "openuni442348"

automatic_scaling:
  max_instances: 1
