runtime: python310
env: standard
service: bookstore-api # <-- Added/Modified: Custom service name

instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  API_KEY: "openuni442348"

handlers:
- url: /.*
  script: auto
  secure: always
  login: optional